### ISSUE TITLE
Fatal errors result in an empty 500 response

### ISSUE THREAD

**Issue by shadowhand** [middlewares/whoops#2]
With this middleware enabled any `E_ERROR` that is triggered during inner middleware execution will result in a HTTP 500 with an empty body.

This is because Whoops uses an output buffer to render fatal errors as part of the shutdown handler, and this middleware [throws away the output buffer](https://github.com/middlewares/whoops/blob/master/src/Whoops.php#L86-L90) that contains the error message.

I tried numerous things to work around this but couldn't come up with a good way to do it in PHP <7.0. I don't really expect this issue to be resolved but I did want it documented.

**Comment by oscarotero** [comment]
That's interesting. I just created a branch with a bugfix. Can you test it, please?

**Comment by oscarotero** [comment]
Ok, fixed in 0.4.1.
