### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by arokettu** [middlewares/whoops#8]
Tests almost pass, there is one problem with the test itself:

```php
$this->assertNotFalse(strpos((string) $response->getBody(), 'Undefined variable: b'));
```

The message has changed and now contains dollar sign: `PHP Warning:  Undefined variable $b`

Obvious blocker as I understand: https://github.com/middlewares/utils/issues/22

**Comment by oscarotero** [comment]
Thanks. I just released 2.0.1 with support for PHP 8
